### ISSUE TITLE
deep_merge and basename functions conflict with puppetlabs-stdlib

### ISSUE THREAD

**Issue by vchepkov** [kayak/puppet-r9util#2]
deep_merge and basename functions installed by the module overrides stdlib functions

/etc/puppetlabs/code/environments/development/modules/r9util/lib/puppet/parser/functions/basename.rb
/etc/puppetlabs/code/environments/development/modules/stdlib/lib/puppet/parser/functions/basename.rb

/etc/puppetlabs/code/environments/development/modules/r9util/lib/puppet/parser/functions/deep_merge.rb
/etc/puppetlabs/code/environments/development/modules/stdlib/lib/puppet/parser/functions/deep_merge.rb

**Comment by NeilHanlon** [comment]
I want to say these were overridden on purpose for our specific use cases, but @chqr or @vibro might have a better idea.

**Comment by vibro** [comment]
This has been fixed in 0.0.10: https://github.com/kayak/puppet-r9util/commit/9dae0a4848b9e9099cedcbce5e48d40a0f71be3c

The functions have been changed to add the prefix "r9".
